### ISSUE TITLE
Network healthchecks

### ISSUE THREAD

**Issue by MaxRink** [telekom/das-schiff-network-operator#32]
Ideally we dont have applications schedule on nodes that have broken networking.

based upon #31 network-operator could perform basic checks like "are all interfaces that i expect up and running"
"Is FRR running" or "can i reach x" before removing the taint from the node

Failing those checks would ideally emit both events and metrics for why its failing

**Comment by chdxD1** [comment]
- Are all Interfaces up and running:
  We should be able to pass a list of interfaces to check. We are most interested in hardware interfaces
- Is FRR running
  a check using systemd is fine (systemd is already mounted because it is used for reload anyway)
- Can I reach X
  An address + port can be passed to the operator to check basic TCP reachability (which should suffice for our case)
